/**
 * KETABI PHOTO-BOOK KEEPSAKES — template registry (single source of truth).
 *
 * Photo books are ordinary `orders` rows with `book_slug` = a template slug
 * (e.g. "about-mama") plus `photo_data` jsonb. They reuse the existing
 * orders / worker / approval / checkout / email rails — this file only adds
 * the per-template content (title, labels, default captions, dedication, the
 * verified dua, accent) shared by the UI and the print worker's intent.
 *
 * The dua Arabic is NOT stored here — it is imported from keepsakeDuas.json
 * (generated by worker/build_keepsake_duas.py, sliced from an authoritative
 * Qur'an dataset) so it is correct by construction and identical to print.
 */
import duas from "./keepsakeDuas.json";

export const PHOTOBOOK_SLUGS = [
  "about-mama",
  "about-baba",
  "about-grandma",
  "about-grandpa",
  "about-spouse",
  "about-baby",
  "our-ramadan",
] as const;
export type PhotobookSlug = (typeof PHOTOBOOK_SLUGS)[number];

export function isPhotobookSlug(slug: string): slug is PhotobookSlug {
  return (PHOTOBOOK_SLUGS as readonly string[]).includes(slug);
}

/** The verified dua printed on the dua page. Render EXACTLY — do not alter a
 *  glyph. Sourced from keepsakeDuas.json. */
export type PhotobookDua = {
  arabic: string;
  translit: string;
  english: string;
  ref: string;
  label?: string;
};

/** Per-category accent — the one colour that differentiates the line. */
export type PhotobookAccent = { main: string; deep: string; dark: string };

export type PhotobookTemplate = {
  slug: PhotobookSlug;
  /** Storefront/product title. */
  title: string;
  /** Field labels shown in the builder. */
  recipientLabel: string;
  /** Example placeholder for the recipient name field. */
  recipientPlaceholder: string;
  authorLabel: string;
  authorPlaceholder: string;
  /** Whether the cover has a small framed photo window. */
  coverPhoto: boolean;
  /** Heartfelt dedication line (rendered under the recipient's name). Mirrors
   *  worker/pipeline/photobook_pipeline.py DEDICATIONS — keep in sync. */
  dedication: string;
  /** Editable default captions — one per photo page (20). */
  defaultCaptions: string[];
  /** Verified dua for the dua page (from keepsakeDuas.json). */
  dua: PhotobookDua;
  /** Subtle category accent (hex). Mirrors the worker's ACCENTS. */
  accent: PhotobookAccent;
  /** Short storefront copy. */
  blurb: string;
  /** Storefront card subtitle. */
  value: string;
};

const D = duas as Record<string, PhotobookDua>;

const ACCENTS: Record<PhotobookSlug, PhotobookAccent> = {
  "about-mama": { main: "#B5975C", deep: "#967A46", dark: "#D0B678" },
  "about-baba": { main: "#607080", deep: "#485868", dark: "#96A8BA" },
  "about-grandma": { main: "#BA8A80", deep: "#9A6C64", dark: "#D6ACA0" },
  "about-grandpa": { main: "#4A6C68", deep: "#365450", dark: "#8CACA6" },
  "about-spouse": { main: "#AA6462", deep: "#8C4E4C", dark: "#D09692" },
  "about-baby": { main: "#849EB2", deep: "#668094", dark: "#B0C6D6" },
  "our-ramadan": { main: "#2D6C56", deep: "#205240", dark: "#78A892" },
};

const ABOUT_MAMA: PhotobookTemplate = {
  slug: "about-mama",
  title: "Everything I Love About Mama",
  recipientLabel: "Mama's name",
  recipientPlaceholder: "e.g. Mama, Ummi, Mom",
  authorLabel: "Your name",
  authorPlaceholder: "e.g. Yusuf",
  coverPhoto: true,
  dedication:
    "who taught my heart to say bismillah, and showed me the mercy of Allah long before I had the words for it.",
  defaultCaptions: [
    "Mama, Allah blessed me with you.",
    "You are the first dua Allah answered for me.",
    "You teach me to love Allah.",
    "I love praying right beside you.",
    "Thank you for every duʿā you make for me.",
    "You fill our home with barakah.",
    "Your hugs make everything better.",
    "You read to me until my eyes grow sleepy.",
    "When I'm scared, you remind me Allah is near.",
    "I love the way you say bismillah before everything.",
    "You wipe my tears and make a dua over me.",
    "You're the first to make duʿā when I'm sick.",
    "You celebrate every little thing I learn.",
    "Your kitchen smells like love and good things.",
    "You forgive me before I even finish saying sorry.",
    "You are gentle with me on my hardest days.",
    "Being your child is a gift from Allah.",
    "I want to make you proud, in this life and the next.",
    "I pray we're together in Jannah, always.",
    "I love you more than all the stars, Mama.",
  ],
  dua: D["about-mama"],
  accent: ACCENTS["about-mama"],
  blurb:
    "A hardcover keepsake your child fills with their own photos and words — twenty things they love about Mama, sealed with the dua for parents.",
  value: "Your own photos & words, sealed with the dua for parents",
};

const ABOUT_BABA: PhotobookTemplate = {
  slug: "about-baba",
  title: "Everything I Love About Baba",
  recipientLabel: "Baba's name",
  recipientPlaceholder: "e.g. Baba, Abu, Papa",
  authorLabel: "Your name",
  authorPlaceholder: "e.g. Yusuf",
  coverPhoto: true,
  dedication:
    "whose strength and gentle faith first showed me how to walk through this life leaning on Allah.",
  defaultCaptions: [
    "Baba, Allah blessed me with you.",
    "You are an answer to a dua I never had to make.",
    "You teach me to love Allah.",
    "I love standing beside you in salah.",
    "Thank you for every duʿā you make for me.",
    "You work hard so our home is full of barakah.",
    "Your shoulders are the safest place in the world.",
    "You answer my biggest questions about Allah.",
    "When I'm scared, you remind me Allah is the strongest.",
    "I love the way you say bismillah before everything.",
    "You carry me when my legs are tired.",
    "You're the first to make duʿā when I'm sick.",
    "You're proud of me even when I make mistakes.",
    "You make ordinary days feel like an adventure.",
    "You forgive me before I even finish saying sorry.",
    "You are patient with me on my hardest days.",
    "Being your child is a gift from Allah.",
    "I want to make you proud, in this life and the next.",
    "I pray we're together in Jannah, always.",
    "I love you more than all the stars, Baba.",
  ],
  dua: D["about-baba"],
  accent: ACCENTS["about-baba"],
  blurb:
    "A hardcover keepsake your child fills with their own photos and words — twenty things they love about Baba, sealed with the dua for parents.",
  value: "Your own photos & words, sealed with the dua for parents",
};

const ABOUT_GRANDMA: PhotobookTemplate = {
  slug: "about-grandma",
  title: "Everything I Love About Grandma",
  recipientLabel: "Grandma's name",
  recipientPlaceholder: "e.g. Teta, Nani, Grandma",
  authorLabel: "Your name",
  authorPlaceholder: "e.g. Maryam",
  coverPhoto: true,
  dedication:
    "whose dua have followed me all my life, and whose love is a barakah I will never outgrow.",
  defaultCaptions: [
    "Allah blessed our family with you.",
    "Your dua have wrapped around me my whole life.",
    "You tell the best stories about our family.",
    "Your hands have made a thousand meals with love.",
    "I love the way you speak about our deen.",
    "You always have room on your lap and in your heart.",
    "Your home smells like every happy memory.",
    "You slip me treats and a little extra love.",
    "You make every visit feel like Eid.",
    "You taught my parent everything good in them.",
    "Your patience is softer than anyone I know.",
    "You remember every name in every dua.",
    "I love praying beside you.",
    "You keep our family's stories alive.",
    "You forgive before I can even ask.",
    "Your hugs feel like coming home.",
    "Being your grandchild is a gift from Allah.",
    "I pray Allah grants you long life and good health.",
    "I pray we're together in Jannah, always.",
    "I love you more than all the stars, Grandma.",
  ],
  dua: D["about-grandma"],
  accent: ACCENTS["about-grandma"],
  blurb:
    "A hardcover keepsake filled with your own photos and words — twenty things you love about Grandma, sealed with a dua for those who raised us.",
  value: "Your photos & words, sealed with a dua for those who raised us",
};

const ABOUT_GRANDPA: PhotobookTemplate = {
  slug: "about-grandpa",
  title: "Everything I Love About Grandpa",
  recipientLabel: "Grandpa's name",
  recipientPlaceholder: "e.g. Jiddo, Dada, Grandpa",
  authorLabel: "Your name",
  authorPlaceholder: "e.g. Yusuf",
  coverPhoto: true,
  dedication:
    "whose stories, patience and faith are a light passed down through our family.",
  defaultCaptions: [
    "Allah blessed our family with you.",
    "Your dua are a shade over all of us.",
    "You tell the stories no one else remembers.",
    "I love sitting beside you after salah.",
    "You taught my parent to be strong and kind.",
    "Your hands have worked hard for all of us.",
    "You answer my questions with patience.",
    "You make me feel brave.",
    "You remember the old days so beautifully.",
    "I love hearing you recite Qur'an.",
    "You always have wisdom and a little joke.",
    "You taught me to give without being asked.",
    "Your faith is a light passed down to me.",
    "You never miss a chance to make dua for me.",
    "You forgive before I can even ask.",
    "Your blessing means the world to me.",
    "Being your grandchild is a gift from Allah.",
    "I pray Allah grants you long life and good health.",
    "I pray we're together in Jannah, always.",
    "I love you more than all the stars, Grandpa.",
  ],
  dua: D["about-grandpa"],
  accent: ACCENTS["about-grandpa"],
  blurb:
    "A hardcover keepsake filled with your own photos and words — twenty things you love about Grandpa, sealed with a dua for those who raised us.",
  value: "Your photos & words, sealed with a dua for those who raised us",
};

const ABOUT_SPOUSE: PhotobookTemplate = {
  slug: "about-spouse",
  title: "Everything I Love About You",
  recipientLabel: "Their name",
  recipientPlaceholder: "e.g. your husband or wife's name",
  authorLabel: "Your name",
  authorPlaceholder: "e.g. your name",
  coverPhoto: true,
  dedication:
    "my home and my comfort — the one I pray to walk beside, in this life and into Jannah.",
  defaultCaptions: [
    "Alhamdulillah, Allah wrote you into my life.",
    "You are the answer to a dua I made before I knew you.",
    "I love praying Fajr beside you.",
    "You make our house a home full of barakah.",
    "Your patience makes me a better Muslim.",
    "You hold my hand through every hard day.",
    "I love hearing you make dua for us.",
    "You forgive me, again and again.",
    "You believe in me when I forget to.",
    "Our laughter is one of Allah's gifts to me.",
    "You are my comfort, the coolness of my eyes.",
    "I love building this life and this deen with you.",
    "You carry me in your dua wherever I go.",
    "Every ordinary day with you feels like a blessing.",
    "You are my home in this dunya.",
    "I love growing closer to Allah alongside you.",
    "Loving you is part of how I worship Allah.",
    "I pray our love is a sadaqah that lasts.",
    "I pray Allah keeps us together in Jannah.",
    "I love you more, every single year.",
  ],
  dua: D["about-spouse"],
  accent: ACCENTS["about-spouse"],
  blurb:
    "A hardcover keepsake of your love story — twenty things you love about the one Allah chose for you, sealed with the dua for spouses.",
  value: "Your love story, sealed with the dua for spouses",
};

const ABOUT_BABY: PhotobookTemplate = {
  slug: "about-baby",
  title: "Everything We Love About You",
  recipientLabel: "Baby's name",
  recipientPlaceholder: "e.g. Maryam, Yusuf",
  authorLabel: "From",
  authorPlaceholder: "e.g. Mama & Baba",
  coverPhoto: true,
  dedication:
    "an answered dua, and a trust (amanah) from Allah we will cherish all our days.",
  defaultCaptions: [
    "You are an answered dua, little one.",
    "We whispered the adhan into your ear.",
    "We made dua for you before we ever met you.",
    "Allah chose us to be your family.",
    "Your tiny hands hold our whole hearts.",
    "We say bismillah over you every day.",
    "You are an amanah from Allah we will protect.",
    "We pray you grow to love Allah.",
    "Every sleepless night is worth your smile.",
    "We see Allah's mercy in your face.",
    "You made us a family.",
    "We can't wait to teach you your first dua.",
    "You are the coolness of our eyes.",
    "We pray you are of the righteous.",
    "Your laugh is our favorite sound in the world.",
    "We thank Allah for you in every salah.",
    "May your heart always be full of iman.",
    "We pray for Jannah for you, and for us with you.",
    "You are loved beyond measure, by us and by Allah.",
    "Welcome to the world, our little blessing.",
  ],
  dua: D["about-baby"],
  accent: ACCENTS["about-baby"],
  blurb:
    "A hardcover keepsake for your little one — twenty things you love about them, sealed with a dua for righteous children. Perfect for an Aqiqah or first year.",
  value: "For your little one, sealed with a dua for righteous children",
};

const OUR_RAMADAN: PhotobookTemplate = {
  slug: "our-ramadan",
  title: "Everything I Love About Ramadan",
  recipientLabel: "What you're celebrating",
  recipientPlaceholder: "e.g. Ramadan or Eid",
  authorLabel: "Your family",
  authorPlaceholder: "e.g. The Aziz family",
  coverPhoto: true,
  dedication:
    "the month our home fills with light, and our hearts draw closer to Allah and to one another.",
  defaultCaptions: [
    "The first crescent moon of Ramadan.",
    "Suhoor together before the sky turns light.",
    "The adhan that means it's time to break our fast.",
    "Dates and water, and a whispered alhamdulillah.",
    "Standing together for taraweeh.",
    "The smell of our kitchen at iftar.",
    "Giving sadaqah with our own hands.",
    "Reading Qur'an as a family.",
    "Lanterns and lights around our home.",
    "Making dua in the last ten nights.",
    "Searching for Laylatul Qadr together.",
    "Helping prepare the iftar table.",
    "Forgiving each other and starting fresh.",
    "The quiet of the masjid at night.",
    "Learning a new surah this month.",
    "Sharing food with our neighbors.",
    "The excitement the night before Eid.",
    "New clothes and Eid morning prayer.",
    "Hugging everyone and saying Eid Mubarak.",
    "A whole month that brought us closer to Allah.",
  ],
  dua: D["our-ramadan"],
  accent: ACCENTS["our-ramadan"],
  blurb:
    "A hardcover keepsake of your family's Ramadan & Eid — twenty things you love about the month, sealed with a dua for your family.",
  value: "Your family's Ramadan & Eid, sealed with a dua for your family",
};

export const PHOTOBOOK_TEMPLATES: Record<PhotobookSlug, PhotobookTemplate> = {
  "about-mama": ABOUT_MAMA,
  "about-baba": ABOUT_BABA,
  "about-grandma": ABOUT_GRANDMA,
  "about-grandpa": ABOUT_GRANDPA,
  "about-spouse": ABOUT_SPOUSE,
  "about-baby": ABOUT_BABY,
  "our-ramadan": OUR_RAMADAN,
};

/** Storefront display order for the keepsake line. */
export const PHOTOBOOK_ORDER: PhotobookSlug[] = [
  "about-mama",
  "about-baba",
  "about-grandma",
  "about-grandpa",
  "about-spouse",
  "about-baby",
  "our-ramadan",
];

export function getPhotobookTemplate(
  slug: string
): PhotobookTemplate | undefined {
  return isPhotobookSlug(slug) ? PHOTOBOOK_TEMPLATES[slug] : undefined;
}

/** Number of customer photo pages (caption + photo) per template. */
export function photobookSpreadCount(slug: PhotobookSlug): number {
  return PHOTOBOOK_TEMPLATES[slug].defaultCaptions.length;
}

/** Shape of orders.photo_data. */
export type PhotobookPage = { photo_url: string; caption: string };
export type PhotobookData = {
  recipient_name: string;
  author_name: string;
  cover_photo_url: string;
  pages: PhotobookPage[];
};

/** The Stripe/receipt product title for a photo-book order. */
export function photobookOrderTitle(
  slug: string,
  recipientName?: string | null
): string {
  const t = getPhotobookTemplate(slug);
  if (!t) return "Ketabi Studio Keepsake";
  const r = (recipientName || "").trim();
  if (!r) return t.title;
  if (slug === "our-ramadan") return `Everything I Love About ${r}`;
  const verb = slug === "about-baby" ? "We Love" : "I Love";
  return `Everything ${verb} About ${r}`;
}
